name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./SoundTest
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./SoundTest
    - uses: actions/upload-artifact@v4
      name: "Upload generated APK"
      with:
        name: data-over-sound.apk
        path: /home/runner/work/Data-over-sound/Data-over-sound/SoundTest/app/build/outputs/apk/debug/app-debug.apk
